import React, { createContext, useCallback, useContext, useMemo, useState } from "react";

const translations = {
  en: {
    brand: {
      title: "World Cup",
      subtitle: "Predictions",
    },
    language: {
      english: "English",
      amharic: "Amharic",
      oromifa: "Oromifa",
    },
    common: {
      loading: "Loading...",
      back: "Back",
      open: "Open",
      locked: "Locked",
      saved: "Saved",
      pending: "Pending",
      none: "None",
      select: "Select",
      yes: "Yes",
      no: "No",
      cancel: "Cancel",
      save: "Save",
      remove: "Remove",
      validating: "Validating...",
      pointsShort: "{{count}} pts",
    },
    currency: {
      birr: "Birr",
      amount: "{{amount}} Birr",
      pool: "{{amount}} Birr pool",
    },
    nav: {
      home: "Home page",
      groupStage: "Group stage",
      playoffs: "Play offs",
    },
    profile: {
      open: "Open profile",
      defaultName: "Telegram Player",
      connectedAccount: "Connected account",
      offline: "Telegram sync offline",
      noPools: "No joined pools yet.",
      joinedPools: "Joined pools",
      pool: "Pool",
      rank: "Rank",
      points: "Points",
      totalPoints: "Total points",
      bestRank: "Best rank",
      lockedGroups: "Locked groups",
      account: "Account",
    },
    betSlip: {
      bet: "Bet",
      bets: "Bets",
      title: "Bet slip",
      oneSelection: "1 selection",
      selections: "{{count}} selections",
      saveToPools: "Save to pools",
      joinFirst: "Join a pool first.",
      selectPool: "Select at least one joined pool before saving bets.",
      success: "Bets saved successfully.",
      failed: "Could not save bets.",
      minimize: "Minimize bet slip",
      saving: "Saving...",
    },
    home: {
      pools: {
        title: "Choose your pool",
        subtitle: "Pick a competition tier and jump into the predictions.",
        all: "All pools",
        totalPrize: "Total prize pool",
        players: "Players",
        spotsLeft: "Spots left",
        joinedProgress: "Joined {{count}}%",
        first: "1st",
        second: "2nd",
        third: "3rd",
      },
      matches: {
        title: "Today matches",
        subtitle: "Tap a team to place your bets.",
        betMore: "Bet more",
        betNow: "Bet now",
      },
      leaderboards: {
        title: "Leaderboards",
        subtitle: "See who is leading the pools right now.",
        viewAll: "View all",
      },
    },
    poolSelection: {
      eyebrow: "Pool selection",
      title: "Choose Your Competition Pool",
      subtitle:
        "Compare entry amounts, prize totals, participation, and rules before joining the group-stage competition.",
      loading: "Loading pools...",
      noPools: "No pools available yet.",
      connectTelegram: "Connect Telegram before joining a pool.",
      failedLoad: "Failed to load pools.",
      failedJoin: "Failed to join pool.",
      screenshotReadFailed: "Could not read screenshot.",
      pasteReceiptFirst: "Paste the Telebirr message or receipt link first.",
      uploadScreenshotFirst: "Upload a Telebirr screenshot first.",
      currentParticipants: "{{count}} current participants",
      totalPrize: "Total Prize",
      spotsRemaining: "{{count}} spots remaining",
      percentFull: "{{count}}% full",
      poolRules: "Pool Rules",
      tournamentProgression: "Tournament Progression",
      pointSystem: "Point System",
      rewardStructure: "Reward Structure",
      joining: "Joining...",
      continue: "Continue With This Pool",
      join: "Join Pool",
      poolTitle: "{{amount}} Birr Pool",
      payTitle: "Pay {{amount}} Birr in Telebirr",
      payBody: "Send exactly {{amount}} Birr for the {{amount}} Birr pool, then paste the Telebirr message/link or upload a screenshot.",
      message: "Message",
      screenshot: "Screenshot",
      receiptPlaceholder: "Paste the Telebirr sent message or receipt link...",
      screenshotPreviewAlt: "Telebirr payment screenshot preview",
      validatePayment: "Validate Payment",
    },
    dashboard: {
      eyebrow: "Dashboard",
      title: "Your Tournament Control Center",
      subtitle:
        "Track performance, jump into daily predictions, and monitor progress through the group stage.",
      warning: "Join a pool to activate competition tracking.",
      joinPool: "Join Pool",
      cards: {
        currentRank: "Current Rank",
        totalPoints: "Total Points",
        predictionAccuracy: "Prediction Accuracy",
        currentStreak: "Current Streak",
        poolPosition: "Pool Position",
        qualificationStatus: "Qualification Status",
        inZone: "In Zone",
        pending: "Pending",
        noPool: "No pool",
      },
      progress: {
        title: "Tournament Progress",
        currentDay: "Current Tournament Day",
        currentStage: "Current Stage",
        completedMatches: "Completed Matches",
        remainingMatches: "Remaining Matches",
        todayCount: "Today's Match Count",
      },
      actions: {
        predictToday: "Predict Today's Matches",
        viewRankings: "View Rankings",
        myPredictions: "My Predictions",
        tournamentStatus: "Tournament Status",
      },
      readiness: {
        title: "Prediction Readiness",
        groupPredictions: "Group predictions",
        dailyPredictions: "Daily match predictions",
        selectedPool: "Selected pool",
        complete: "{{count}}% complete",
        saved: "{{count}} saved",
      },
      activity: {
        title: "Recent Activity",
      },
    },
    group: {
      eyebrow: "Group stage predictions",
      title: "Submit Group Rankings",
      subtitle:
        "Choose first through fourth place for every group. Once locked, these long-term predictions stay read-only throughout the group stage.",
      actions: {
        pools: "Pools",
        lock: "Lock Predictions",
      },
      warning: "Select a pool before locking group predictions.",
      warningChoose: "Choose Pool",
      summary: {
        completion: "Completion",
        lockedGroups: "Locked groups",
        completed: "Completed Groups",
        remaining: "Remaining Groups",
        status: "Status",
        locked: "Locked",
        open: "Open",
      },
      advancing: {
        title: "Selected Advancing Teams",
        empty: "No advancing teams selected yet.",
      },
      position: {
        first: "First place",
        second: "Second place",
        third: "Third place",
        fourth: "Fourth place",
        notSelected: "Not selected",
      },
      selectTeam: "Select team",
      modal: {
        title: "Predictions Become Permanently Locked",
        body: "After final submission, group-stage selections become read-only and cannot be edited.",
        review: "Review Again",
        confirm: "Confirm Lock",
      },
      predictionPool: "Prediction pool",
      selectPool: "Select pool",
      joinAnotherPool: "Join another pool",
      possiblePoints: "Possible points",
      groupSaved: "{{group}} saved",
      groupLocked: "{{group}} locked",
      saveFailed: "Failed to save group",
      lockFailed: "Failed to lock group",
      lockGroup: "Lock {{group}}",
    },
    matches: {
      eyebrow: "Daily match predictions",
      title: "Predict Today's Matches",
      subtitle:
        "Switch match days, save every open prediction, and review locked or completed match cards after kickoff.",
      tabsAria: "Match days",
      kickoffReached: "Kickoff reached",
      meta: {
        saved: "Prediction saved",
        closed: "Prediction closed",
        open: "Prediction open",
      },
      outcome: {
        title: "Match outcome",
        homeWin: "{{team}} wins",
        draw: "Draw",
        awayWin: "{{team}} wins",
      },
      score: {
        title: "Exact score",
      },
      additional: {
        title: "Additional prediction options",
        firstScore: "First team to score",
        bothScore: "Both teams score",
        totalCorners: "Total corners",
        cleanSheet: "Clean sheet",
        select: "Select",
        noGoal: "No goal",
        none: "None",
        placeholder: "Example: 9",
      },
      bonus: {
        penalty: "Penalty scored",
        redCard: "Red card",
        lateGoal: "Goal after 80 minutes",
      },
      actions: {
        save: "Save Prediction",
        saved: "Prediction saved",
      },
      locked: {
        noSelection: "Prediction closed. No submitted selections found.",
        submitted: "Submitted prediction",
        outcomePick: "Outcome pick",
        finalResult: "Final result",
        pointsEarned: "Points earned",
        notSelected: "Not selected",
      },
    },
    leaderboard: {
      eyebrow: "Leaderboard",
      title: "Pool Rankings",
      subtitle:
        "Filter rankings, track movement, and see how close you are to the qualification zone.",
      filter: {
        pool: "Pool",
        allPools: "All pools",
        ranking: "Ranking",
        overall: "Overall",
        myPool: "My pool",
        qualification: "Qualification zone",
        time: "Time",
        groupStage: "Group stage",
        today: "Today",
        allTime: "All time",
      },
      table: {
        rank: "Rank",
        user: "User",
        points: "Points",
        accuracy: "Accuracy",
        streak: "Streak",
        move: "Move",
      },
      movement: {
        up: "Upward movement",
        down: "Downward movement",
        stable: "Stable ranking",
      },
      panels: {
        top: "Top Performers",
        closest: "Closest Competitors",
        zone: "Qualification Zone",
        topPercent: "Top 40%",
        currentRank: "You are currently #{{rank}}.",
        joinPool: "Join a pool to appear here.",
      },
      you: "You",
    },
    history: {
      eyebrow: "My predictions",
      title: "Prediction History",
      subtitle: "Review your locked group selections and every saved daily match prediction.",
      stats: {
        totalPredictions: "Total Predictions",
        correctPredictions: "Correct Predictions",
        accuracy: "Accuracy Percentage",
        totalExact: "Total Exact Scores",
        totalPoints: "Total Points",
      },
      groups: {
        title: "Group Predictions",
        locked: "Locked",
        open: "Open",
        notSelected: "Not selected",
      },
      daily: {
        title: "Daily Predictions",
        submitted: "Submitted Prediction",
        notSubmitted: "Not submitted",
        finalResult: "Final Result",
        pending: "Pending",
        pointsGained: "Points Gained",
        status: "Status",
      },
    },
    deposit: {
      title: "Deposit",
      payTo: "Pay to this number:",
      chooseInput: "Choose receipt input type",
      modeText: "Paste text/link",
      modeScreenshot: "Upload screenshot",
      pasteLabel: "Paste the message or receipt link here",
      pastePlaceholder: "Paste receipt text or transaction link...",
      uploadLabel: "Upload payment screenshot",
      chooseDifferent: "Choose different screenshot",
      chooseImage: "Choose screenshot image",
      fileHint: "PNG, JPG or WEBP up to 5MB",
      selected: "Selected: {{name}}",
      confirmPaid: "I confirm that I made the payment",
      checkReceipt: "Check Receipt",
      verifying: "Verifying...",
      verifyingPayment: "Verifying payment...",
      errorConfirm: "Please check the confirmation box before submitting.",
      errorEmptyText: "Please paste your message or receipt link.",
      errorNoScreenshot: "Please upload a screenshot first.",
      errorReceiptFailed: "Receipt check failed.",
      errorOcrFailed: "Could not read screenshot.",
      successDefault: "Receipt check complete. Status: {{status}}.",
      errorBackend: "Failed to connect to backend API.",
    },
    withdraw: {
      title: "Withdraw",
      balance: "Your Balance",
      min: "Minimum withdraw: {{min}} Birr",
      max: "Maximum withdraw: {{max}} Birr",
      label: "Withdraw amount",
      placeholder: "Enter amount to withdraw",
      submit: "Withdraw",
      sending: "Sending...",
      errorUser: "User not found. Please open from Telegram app.",
      errorMin: "Minimum withdraw amount is {{min}}.",
      errorMax: "Withdraw amount is greater than your balance.",
      errorFailed: "Withdraw failed.",
      errorRequestFailed: "Failed to send withdraw request.",
      successDefault: "Withdraw request sent successfully.",
    },
    game: {
      loading: "Loading Game...",
      fee: "Fee",
      pick: "Pick",
      lay: "Lay",
      empty: "Empty",
      player: "Player",
      gameOver: "Game Over",
      winner: "Winner",
      pattern: "Pattern",
      reason: "Reason",
      ended: "Ended",
      notAvailable: "N/A",
      leave: "Leave",
      starting: "Starting...",
      playAgain: "Play Again",
      you: "You",
      waiting: "Waiting for cards...",
      win: "Win",
      errorNetwork: "Network error. Could not connect to server.",
      errorAction: "Action failed",
      errorPickFirst: "You must pick a card before you can lay one.",
      errorAlreadyPicked: "You already picked! You must lay a card.",
      errorWinningHand: "Winning hand must be 4-3-3-1.",
      statusFee: "Fee: {{amount}} Birr",
      statusPlayer: "Player {{id}}",
      statusWinner: "Winner: Player {{id}}",
      statusPattern: "Pattern: {{pattern}}",
      statusReason: "Reason: {{reason}}",
      statusEnded: "Ended: {{ended}}",
    },
  },
  am: {
    brand: {
      title: "የዓለም ዋንጫ",
      subtitle: "ትንበያዎች",
    },
    language: {
      english: "እንግሊዝኛ",
      amharic: "አማርኛ",
      oromifa: "ኦሮምኛ",
    },
    common: {
      loading: "በመጫን ላይ...",
      back: "ተመለስ",
      open: "ክፍት",
      locked: "ተቆልፏል",
      pending: "በጥበቃ ላይ",
      none: "የለም",
      select: "ይምረጡ",
      yes: "አዎ",
      no: "አይ",
      saved: "ተቀምጧል",
      cancel: "ሰርዝ",
      save: "አስቀምጥ",
      remove: "አስወግድ",
      validating: "በማረጋገጥ ላይ...",
      pointsShort: "{{count}} ነጥብ",
    },
    currency: {
      birr: "ብር",
      amount: "{{amount}} ብር",
      pool: "{{amount}} ብር ፑል",
    },
    nav: {
      home: "መነሻ",
      groupStage: "የቡድን ደረጃ",
      playoffs: "ፕሌይ ኦፍ",
    },
    profile: {
      open: "ፕሮፋይል ክፈት",
      defaultName: "የቴሌግራም ተጫዋች",
      connectedAccount: "የተገናኘ መለያ",
      offline: "ቴሌግራም ከመስመር ውጭ",
      balance: "ቀሪ ብር",
      deposit: "መጨመር",
      withdraw: "መቀነስ",
      noPools: "እስካሁን የተቀላቀሉት ፑል የለም።",
      joinedPools: "የተቀላቀሉ ፑሎች",
      pool: "ፑል",
      rank: "ደረጃ",
      points: "ነጥብ",
      totalPoints: "ጠቅላላ ነጥብ",
      bestRank: "ምርጥ ደረጃ",
      lockedGroups: "የተቆለፉ ቡድኖች",
      account: "መለያ",
    },
    betSlip: {
      bet: "ውርርድ",
      bets: "ውርርዶች",
      title: "የውርርድ ዝርዝር",
      oneSelection: "1 ምርጫ",
      selections: "{{count}} ምርጫዎች",
      saveToPools: "ወደ ፑሎች አስቀምጥ",
      joinFirst: "መጀመሪያ ፑል ይቀላቀሉ።",
      selectPool: "ውርርዶችን ከማስቀመጥ በፊት ቢያንስ አንድ ፑል ይምረጡ።",
      success: "ውርርዶች በተሳካ ሁኔታ ተቀመጡ።",
      failed: "ውርርዶችን ማስቀመጥ አልተቻለም።",
      minimize: "የውርርድ ዝርዝሩን አሳንስ",
      saving: "በማስቀመጥ ላይ...",
    },
    home: {
      pools: {
        title: "ፑልዎን ይምረጡ",
        subtitle: "የውድድር ደረጃ ይምረጡ እና ወደ ትንበያ ይግቡ።",
        all: "ሁሉም ፑሎች",
        totalPrize: "ጠቅላላ የሽልማት ፑል",
        players: "ተጫዋቾች",
        spotsLeft: "ቀሪ ቦታ",
        joinedProgress: "ተቀላቅለዋል {{count}}%",
        first: "1ኛ",
        second: "2ኛ",
        third: "3ኛ",
      },
      matches: {
        title: "የዛሬ ጨዋታዎች",
        subtitle: "ለመዋርድ ቡድን ይጫኑ።",
        betMore: "ተጨማሪ ይዋርዱ",
        betNow: "አሁን ይዋርዱ",
      },
      leaderboards: {
        title: "የመሪዎች ሰንጠረዥ",
        subtitle: "አሁን ፑሎችን የሚመሩትን ይመልከቱ።",
        viewAll: "ሁሉን ይመልከቱ",
      },
    },
    poolSelection: {
      eyebrow: "ፑል ምርጫ",
      title: "የውድድር ፑልዎን ይምረጡ",
      subtitle:
        "የመግቢያ መጠን፣ የሽልማት ድምር፣ ተሳትፎ እና ህጎች ያነጋግሩ።",
      loading: "ፑሎች በመጫን ላይ...",
      noPools: "እስካሁን የሚገኙ ፑሎች የሉም።",
      connectTelegram: "ፑል ከመግባት በፊት ቴሌግራም ያገናኙ።",
      failedLoad: "ፑሎች መጫን አልተሳካም።",
      failedJoin: "ፑል መቀላቀል አልተሳካም።",
      screenshotReadFailed: "ስክሪንሾቱን ማንበብ አልተቻለም።",
      pasteReceiptFirst: "መጀመሪያ የቴሌብር መልዕክት ወይም ሊንክ ይለጥፉ።",
      uploadScreenshotFirst: "መጀመሪያ የቴሌብር ስክሪንሾት ይጫኑ።",
      currentParticipants: "{{count}} የአሁን ተሳታፊዎች",
      totalPrize: "ጠቅላላ ሽልማት",
      spotsRemaining: "{{count}} ቦታ ቀርቷል",
      percentFull: "{{count}}% ተሞልቷል",
      poolRules: "የፑል ህጎች",
      tournamentProgression: "የውድድር እድገት",
      pointSystem: "የነጥብ ስርዓት",
      rewardStructure: "የሽልማት አወቃቀር",
      joining: "በመቀላቀል ላይ...",
      continue: "በዚህ ፑል ቀጥል",
      join: "ፑል ተቀላቀል",
      poolTitle: "{{amount}} ብር ፑል",
      payTitle: "{{amount}} ብር በቴሌብር ይክፈሉ",
      payBody: "ለ{{amount}} ብር ፑል በትክክል {{amount}} ብር ይላኩ፣ ከዚያ የቴሌብር መልዕክት/ሊንክ ይለጥፉ ወይም ስክሪንሾት ይጫኑ።",
      message: "መልዕክት",
      screenshot: "ስክሪንሾት",
      receiptPlaceholder: "የቴሌብር መልዕክት ወይም ሊንክ ይለጥፉ...",
      screenshotPreviewAlt: "የቴሌብር ክፍያ ስክሪንሾት ቅድመ እይታ",
      validatePayment: "ክፍያ አረጋግጥ",
    },
    dashboard: {
      eyebrow: "ዳሽቦርድ",
      title: "የውድድር መቆጣጠሪያዎ",
      subtitle:
        "አፈጻጸምዎን ይከታተሉ፣ የዛሬ ትንበያ ይግቡ እና እድገቱን ይመልከቱ።",
      warning: "ውድድር መከታተል ለማንቃት ፑል ይቀላቀሉ።",
      joinPool: "ፑል ተቀላቀል",
      cards: {
        currentRank: "የአሁኑ ደረጃ",
        totalPoints: "ጠቅላላ ነጥብ",
        predictionAccuracy: "የትንበያ ትክክለኛነት",
        currentStreak: "የአሁኑ ተከታታይ",
        poolPosition: "የፑል ቦታ",
        qualificationStatus: "የብቃት ሁኔታ",
        inZone: "በዞን",
        pending: "በጥበቃ ላይ",
        noPool: "ፑል የለም",
      },
      progress: {
        title: "የውድድር እድገት",
        currentDay: "የአሁኑ የውድድር ቀን",
        currentStage: "የአሁኑ ደረጃ",
        completedMatches: "የተጠናቀቁ ጨዋታዎች",
        remainingMatches: "የቀሩ ጨዋታዎች",
        todayCount: "የዛሬ ጨዋታ ብዛት",
      },
      actions: {
        predictToday: "የዛሬ ጨዋታዎችን ተንብይ",
        viewRankings: "ደረጃዎችን ይመልከቱ",
        myPredictions: "ትንበያዬ",
        tournamentStatus: "የውድድር ሁኔታ",
      },
      readiness: {
        title: "የትንበያ ዝግጅት",
        groupPredictions: "የቡድን ትንበያ",
        dailyPredictions: "የዕለት ጨዋታ ትንበያ",
        selectedPool: "የተመረጠ ፑል",
        complete: "{{count}}% ተጠናቅቋል",
        saved: "{{count}} ተቀምጧል",
      },
      activity: {
        title: "የቅርብ ጊዜ እንቅስቃሴ",
      },
    },
    group: {
      eyebrow: "የቡድን ደረጃ ትንበያ",
      title: "የቡድን ደረጃ ይላኩ",
      subtitle:
        "ለእያንዳንዱ ቡድን ከ1 እስከ 4 ቦታዎችን ይምረጡ። ከተቆለፈ በኋላ መለወጥ አይቻልም።",
      actions: {
        pools: "ፑሎች",
        lock: "ትንበያ ተቆልፍ",
      },
      warning: "ትንበያ ከመቆለፍ በፊት ፑል ይምረጡ።",
      warningChoose: "ፑል ይምረጡ",
      summary: {
        completion: "ማጠናቀቅ",
        completed: "የተጠናቀቁ ቡድኖች",
        remaining: "የቀሩ ቡድኖች",
        status: "ሁኔታ",
        locked: "ተቆልፏል",
        open: "ክፍት",
      },
      advancing: {
        title: "የተመረጡ የሚያልፉ ቡድኖች",
        empty: "የሚያልፉ ቡድኖች አልተመረጡም።",
      },
      position: {
        first: "1ኛ ቦታ",
        second: "2ኛ ቦታ",
        third: "3ኛ ቦታ",
        fourth: "4ኛ ቦታ",
        notSelected: "አልተመረጠም",
      },
      selectTeam: "ቡድን ይምረጡ",
      modal: {
        title: "ትንበያዎች ዘላቂ ሆነዋል",
        body: "ከመጨረሻ እንደተላኩ በኋላ መለወጥ አይቻልም።",
        review: "ዳግም አስረጉ",
        confirm: "ተረጋግጥ እና ተቆልፍ",
      },
    },
    matches: {
      eyebrow: "ዕለታዊ ትንበያ",
      title: "የዛሬ ጨዋታዎችን ተንብይ",
      subtitle:
        "የቀን ጨዋታዎችን ይቀይሩ፣ ክፍት ትንበያዎችን ያስቀምጡ፣ እና ከጀምሮ በኋላ የተቆለፉ ጨዋታዎችን ይመልከቱ።",
      tabsAria: "የጨዋታ ቀኖች",
      kickoffReached: "መጀመሪያ ደርሷል",
      meta: {
        saved: "ትንበያ ተቀምጧል",
        closed: "ትንበያ ተዘግቷል",
        open: "ትንበያ ክፍት",
      },
      outcome: {
        title: "የጨዋታ ውጤት",
        homeWin: "{{team}} አሸንፏል",
        draw: "እኩል",
        awayWin: "{{team}} አሸንፏል",
      },
      score: {
        title: "ትክክለኛ ውጤት",
      },
      additional: {
        title: "ተጨማሪ ትንበያ አማራጮች",
        firstScore: "መጀመሪያ ግብ የሚያስመዝግብ ቡድን",
        bothScore: "ሁለቱም ቡድኖች ይመዝግባሉ",
        totalCorners: "ጠቅላላ ኮርነሮች",
        cleanSheet: "ንጹህ ጨዋታ",
        select: "ይምረጡ",
        noGoal: "ግብ የለም",
        none: "የለም",
        placeholder: "ለምሳሌ፡ 9",
      },
      bonus: {
        penalty: "ፔናልቲ ተመዝግቧል",
        redCard: "ቀይ ካርድ",
        lateGoal: "ከ80 ደቂቃ በኋላ ግብ",
      },
      actions: {
        save: "ትንበያ አስቀምጥ",
        saved: "ትንበያ ተቀምጧል",
      },
      locked: {
        noSelection: "ትንበያ ተዘግቷል። የተላኩ ምርጫዎች አልተገኙም።",
        submitted: "የተላከ ትንበያ",
        outcomePick: "የውጤት ምርጫ",
        finalResult: "የመጨረሻ ውጤት",
        pointsEarned: "የተገኙ ነጥቦች",
        notSelected: "አልተመረጠም",
      },
    },
    leaderboard: {
      eyebrow: "ደረጃ",
      title: "የፑል ደረጃዎች",
      subtitle:
        "ደረጃዎችን ያጣሩ፣ እንቅስቃሴን ይመልከቱ እና ከብቃት ዞን ስንት እንደምትርቁ ይዩ።",
      filter: {
        pool: "ፑል",
        allPools: "ሁሉም ፑሎች",
        ranking: "ደረጃ",
        overall: "አጠቃላይ",
        myPool: "የእኔ ፑል",
        qualification: "የብቃት ዞን",
        time: "ጊዜ",
        groupStage: "የቡድን ደረጃ",
        today: "ዛሬ",
        allTime: "ሁልጊዜ",
      },
      table: {
        rank: "ደረጃ",
        user: "ተጠቃሚ",
        points: "ነጥቦች",
        accuracy: "ትክክለኛነት",
        streak: "ተከታታይ",
        move: "እንቅስቃሴ",
      },
      movement: {
        up: "ወደ ላይ እንቅስቃሴ",
        down: "ወደ ታች እንቅስቃሴ",
        stable: "የተረጋጋ ደረጃ",
      },
      panels: {
        top: "ከፍተኛ አፈጻጸሞች",
        closest: "ቅርብ ተወዳዳሪዎች",
        zone: "የብቃት ዞን",
        topPercent: "ከፍተኛ 40%",
        currentRank: "አሁን ደረጃዎ #{{rank}} ነው።",
        joinPool: "እዚህ ለማየት ፑል ተቀላቀል።",
      },
      you: "አንተ/አንቺ",
    },
    history: {
      eyebrow: "የእኔ ትንበያ",
      title: "የትንበያ ታሪክ",
      subtitle: "የተቆለፉ የቡድን ምርጫዎችን እና የዕለት ትንበያዎችን ይመልከቱ።",
      stats: {
        totalPredictions: "ጠቅላላ ትንበያዎች",
        correctPredictions: "ትክክለኛ ትንበያዎች",
        accuracy: "የትክክለኛነት መቶኛ",
        totalExact: "ጠቅላላ ትክክለኛ ውጤቶች",
        totalPoints: "ጠቅላላ ነጥቦች",
      },
      groups: {
        title: "የቡድን ትንበያ",
        locked: "ተቆልፏል",
        open: "ክፍት",
        notSelected: "አልተመረጠም",
      },
      daily: {
        title: "የዕለት ትንበያ",
        submitted: "የተላከ ትንበያ",
        notSubmitted: "አልተላከም",
        finalResult: "የመጨረሻ ውጤት",
        pending: "በጥበቃ ላይ",
        pointsGained: "የተገኙ ነጥቦች",
        status: "ሁኔታ",
      },
    },
    deposit: {
      title: "መጨመር",
      payTo: "ወደዚህ ቁጥር ይክፈሉ፦",
      chooseInput: "የደረሰኝ አይነት ይምረጡ",
      modeText: "ጽሑፍ/ሊንክ ይለጥፉ",
      modeScreenshot: "ስክሪንሾት ያንቀሳቅሱ",
      pasteLabel: "መልዕክት ወይም የደረሰኝ ሊንክ እዚህ ይለጥፉ",
      pastePlaceholder: "የደረሰኝ ጽሑፍ ወይም የትራንዛክሽን ሊንክ ይለጥፉ...",
      uploadLabel: "የክፍያ ስክሪንሾት ይጫኑ",
      chooseDifferent: "ሌላ ስክሪንሾት ይምረጡ",
      chooseImage: "ስክሪንሾት ምስል ይምረጡ",
      fileHint: "PNG, JPG ወይም WEBP እስከ 5MB",
      selected: "ተመርጧል፦ {{name}}",
      confirmPaid: "ክፍያ እንደፈፀምሁ እገምጽ",
      checkReceipt: "ደረሰኝ ያረጋግጡ",
      verifying: "በማረጋገጥ ላይ...",
      verifyingPayment: "ክፍያ በማረጋገጥ ላይ...",
      errorConfirm: "እባክዎ ከመላክ በፊት ማረጋገጫውን ይመልከቱ።",
      errorEmptyText: "እባክዎ መልዕክት ወይም ሊንክ ይለጥፉ።",
      errorNoScreenshot: "እባክዎ መጀመሪያ ስክሪንሾት ይጫኑ።",
      errorReceiptFailed: "ደረሰኝ ምርመራ አልተሳካም።",
      errorOcrFailed: "ስክሪንሾት ማንበብ አልተቻለም።",
      successDefault: "የደረሰኝ ምርመራ ተጠናቀቀ። ሁኔታ፦ {{status}}.",
      errorBackend: "ከባክንድ ኤፒአይ ጋር መገናኘት አልተቻለም።",
    },
    withdraw: {
      title: "መቀነስ",
      balance: "የእርስዎ ቀሪ ብር",
      min: "ዝቅተኛ መቀነስ: {{min}} ብር",
      max: "ከፍተኛ መቀነስ: {{max}} ብር",
      label: "የመቀነስ መጠን",
      placeholder: "የመቀነስ መጠን ያስገቡ",
      submit: "መቀነስ",
      sending: "በመላክ ላይ...",
      errorUser: "ተጠቃሚ አልተገኘም። ከቴሌግራም መተግበሪያ ይክፈቱ።",
      errorMin: "ዝቅተኛ የመቀነስ መጠን {{min}} ነው።",
      errorMax: "የመቀነስ መጠን ከቀሪ ብርዎ ይበልጣል።",
      errorFailed: "መቀነስ አልተሳካም።",
      errorRequestFailed: "የመቀነስ ጥያቄ መላክ አልተሳካም።",
      successDefault: "የመቀነስ ጥያቄ ተላክ።",
    },
    game: {
      loading: "ጨዋታ በመጫን ላይ...",
      fee: "ክፍያ",
      pick: "ይምረጡ",
      lay: "ጣል",
      empty: "ባዶ",
      player: "ተጫዋች",
      gameOver: "ጨዋታ ተጠናቀቀ",
      winner: "አሸናፊ",
      pattern: "ንድፍ",
      reason: "ምክንያት",
      ended: "ተጠናቀቀ",
      notAvailable: "የለም",
      leave: "ውጣ",
      starting: "በመጀመር ላይ...",
      playAgain: "እንደገና ተጫወት",
      you: "አንተ/አንቺ",
      waiting: "ካርዶችን በመጠበቅ ላይ...",
      win: "አሸንፍ",
      errorNetwork: "የኔትወርክ ስህተት፣ ሰርቨር ጋር መገናኘት አልተቻለም።",
      errorAction: "እርምጃ አልተሳካም",
      errorPickFirst: "መጀመሪያ ካርድ ይምረጡ ከዚያ ትጣሉ።",
      errorAlreadyPicked: "አስቀድሞ ካርድ መርጠዋል! አንድ ካርድ መጣል አለብዎት።",
      errorWinningHand: "የመከበር እጅ 4-3-3-1 መሆን አለበት።",
      statusFee: "ክፍያ: {{amount}} ብር",
      statusPlayer: "ተጫዋች {{id}}",
      statusWinner: "አሸናፊ: ተጫዋች {{id}}",
      statusPattern: "ንድፍ: {{pattern}}",
      statusReason: "ምክንያት: {{reason}}",
      statusEnded: "ተጠናቀቀ: {{ended}}",
    },
  },
  om: {
    brand: {
      title: "World Cup",
      subtitle: "Tilmaamota",
    },
    language: {
      english: "Afaan Ingilizii",
      amharic: "Afaan Amaaraa",
      oromifa: "Afaan Oromoo",
    },
    common: {
      loading: "Fe'aa jira...",
      back: "Deebi'i",
      open: "Banaa",
      locked: "Qufame",
      pending: "Eegamaa",
      none: "Hin jiru",
      select: "Filadhu",
      yes: "Eeyyee",
      no: "Lakki",
    },
    profile: {
      open: "Profaayilii banu",
      defaultName: "Taphataa Telegram",
      connectedAccount: "Akkaawuntii walitti hidhame",
      offline: "Telegram offline",
      balance: "Haftee",
      deposit: "Dabaluu",
      withdraw: "Baafachuu",
    },
    home: {
      pools: {
        title: "Poolii kee filadhu",
        subtitle: "Sadarkaa morkii filadhu; booda tilmaama keessa seeni.",
        all: "Poolii hunda",
        totalPrize: "Badhaasa waliigalaa",
        players: "Taphattoota",
        spotsLeft: "Bakka hafe",
      },
      matches: {
        title: "Taphoota har'a",
        subtitle: "Bet gochuuf garee tuqi.",
        betMore: "Irra caalaa bet",
        betNow: "Amma bet",
      },
      leaderboards: {
        title: "Tarree hooggantootaa",
        subtitle: "Yeroo ammaa eenyu dura ta'e ilaali.",
        viewAll: "Hunda ilaali",
      },
    },
    poolSelection: {
      eyebrow: "Filannoo poolii",
      title: "Poolii morkii filadhu",
      subtitle:
        "Gatii seensaa, badhaasa, hirmaannaa fi seera waliin ilaali.",
      loading: "Poolii fe'aa jira...",
      noPools: "Pooliin hin jiru.",
      connectTelegram: "Poolii seenuuf dura Telegram waliin hidhi.",
      failedLoad: "Poolii fe'uu hin dandeenye.",
      failedJoin: "Poolii seenu hin dandeenye.",
      currentParticipants: "{{count}} hirmaattota ammaa",
      totalPrize: "Badhaasa waliigalaa",
      spotsRemaining: "Bakka {{count}} hafe",
      percentFull: "{{count}}% guutame",
      poolRules: "Seerota poolii",
      tournamentProgression: "Guddina morkii",
      pointSystem: "Sirna qabxii",
      rewardStructure: "Sirna badhaasaa",
      joining: "Seenuu irratti...",
      continue: "Poolii kana itti fufi",
      join: "Poolii seeni",
    },
    dashboard: {
      eyebrow: "Daashboordii",
      title: "Bu'uura too'annoo morkii",
      subtitle:
        "Raawwii kee hordofi, tilmaama guyyoo seeni, fi guddina ilaali.",
      warning: "Hordoffii dandeessuuf poolii seeni.",
      joinPool: "Poolii seeni",
      cards: {
        currentRank: "Sadarkaa ammaa",
        totalPoints: "Qabxii waliigalaa",
        predictionAccuracy: "Sirrii tilmaamaa",
        currentStreak: "Tartiiba ammaa",
        poolPosition: "Iddoo poolii",
        qualificationStatus: "Haala darbuu",
        inZone: "Naannoo keessa",
        pending: "Eegamaa",
        noPool: "Poolii hin jiru",
      },
      progress: {
        title: "Guddina morkii",
        currentDay: "Guyyaa morkii ammaa",
        currentStage: "Sadarkaa ammaa",
        completedMatches: "Taphoota xumuraman",
        remainingMatches: "Taphoota hafe",
        todayCount: "Lakkoofsa taphoota har'a",
      },
      actions: {
        predictToday: "Taphoota har'a tilmaami",
        viewRankings: "Sadarkaa ilaali",
        myPredictions: "Tilmaama koo",
        tournamentStatus: "Haala morkii",
      },
      readiness: {
        title: "Qophii tilmaamaa",
        groupPredictions: "Tilmaama garee",
        dailyPredictions: "Tilmaama taphoota guyyoo",
        selectedPool: "Poolii filatame",
        complete: "{{count}}% xumurame",
        saved: "{{count}} olkaa'ame",
      },
      activity: {
        title: "Sochii dhiyoo",
      },
    },
    group: {
      eyebrow: "Tilmaama sadarkaa garee",
      title: "Sadarkaa garee galchi",
      subtitle:
        "Garee hundaa keessatti 1ffaa hanga 4ffaa filadhu. Erga qufameen booda hin jijjiiramu.",
      actions: {
        pools: "Poolii",
        lock: "Tilmaama qufi",
      },
      warning: "Tilmaama qufuu dura poolii filadhu.",
      warningChoose: "Poolii filadhu",
      summary: {
        completion: "Xumura",
        completed: "Gareewwan xumuraman",
        remaining: "Gareewwan hafe",
        status: "Haala",
        locked: "Qufame",
        open: "Banaa",
      },
      advancing: {
        title: "Gareewwan darbu filataman",
        empty: "Gareewwan darbu hin filatamne.",
      },
      position: {
        first: "Iddoo 1ffaa",
        second: "Iddoo 2ffaa",
        third: "Iddoo 3ffaa",
        fourth: "Iddoo 4ffaa",
        notSelected: "Hin filatamne",
      },
      selectTeam: "Garee filadhu",
      modal: {
        title: "Tilmaamni yeroo hundaa qufame",
        body: "Erga mirkanaa'e booda, jijjiiruun hin danda'amu.",
        review: "Irra deebi'ii ilaali",
        confirm: "Mirkaneessi",
      },
    },
    matches: {
      eyebrow: "Tilmaama taphoota guyyoo",
      title: "Taphoota har'a tilmaami",
      subtitle:
        "Guyyaa taphoota filadhu, tilmaama banaa olkaa'i, fi taphoota qufaman ilaali.",
      tabsAria: "Guyyoota taphoota",
      kickoffReached: "Taphaan eegaleera",
      meta: {
        saved: "Tilmaamni olkaa'ame",
        closed: "Tilmaamni cufame",
        open: "Tilmaamni banaa",
      },
      outcome: {
        title: "Bu'aa taphaa",
        homeWin: "{{team}} mo'ate",
        draw: "Harki wal qixa",
        awayWin: "{{team}} mo'ate",
      },
      score: {
        title: "Qabxii sirrii",
      },
      additional: {
        title: "Filannoo dabalataa",
        firstScore: "Garee jalqabaa galmeessu",
        bothScore: "Gareewwan lamaan ni galmeessu",
        totalCorners: "Corner waliigalaa",
        cleanSheet: "Clean sheet",
        select: "Filadhu",
        noGoal: "Golii hin jiru",
        none: "Hin jiru",
        placeholder: "Fakkeenya: 9",
      },
      bonus: {
        penalty: "Penalty galmeessame",
        redCard: "Kaardii diimaa",
        lateGoal: "Golii daqiiqaa 80 booda",
      },
      actions: {
        save: "Tilmaama olkaa'i",
        saved: "Tilmaamni olkaa'ame",
      },
      locked: {
        noSelection: "Tilmaamni cufame. Filannoo hin argamne.",
        submitted: "Tilmaama galchame",
        outcomePick: "Filannoo bu'aa",
        finalResult: "Bu'aa xumuraa",
        pointsEarned: "Qabxii argame",
        notSelected: "Hin filatamne",
      },
    },
    leaderboard: {
      eyebrow: "Sadarkaa",
      title: "Sadarkaa poolii",
      subtitle:
        "Sadarkaa sirreessi, sochii ilaali, fi naannoo darbuu irraa fageenya ilaali.",
      filter: {
        pool: "Poolii",
        allPools: "Poolii hunda",
        ranking: "Sadarkaa",
        overall: "Waliigalaa",
        myPool: "Poolii koo",
        qualification: "Naannoo darbuu",
        time: "Yeroo",
        groupStage: "Sadarkaa garee",
        today: "Har'a",
        allTime: "Yeroo hunda",
      },
      table: {
        rank: "Sadarkaa",
        user: "Tajaajilamaa",
        points: "Qabxii",
        accuracy: "Sirrii",
        streak: "Tartiiba",
        move: "Sochii",
      },
      movement: {
        up: "Ol ka'uu",
        down: "Gadi bu'uu",
        stable: "Tasgabbaa'aa",
      },
      panels: {
        top: "Raawwii ol'aanaa",
        closest: "Morkitoota dhihoo",
        zone: "Naannoo darbuu",
        topPercent: "Top 40%",
        currentRank: "Sadarkaa kee ammaa #{{rank}} dha.",
        joinPool: "Asitti mul'achuuf poolii seeni.",
      },
      you: "Ati",
    },
    history: {
      eyebrow: "Tilmaama koo",
      title: "Seenaa tilmaamaa",
      subtitle: "Filannoo garee qufame fi tilmaama taphoota guyyoo ilaali.",
      stats: {
        totalPredictions: "Tilmaama waliigalaa",
        correctPredictions: "Tilmaama sirrii",
        accuracy: "Sirrii %",
        totalExact: "Bu'aa sirrii waliigalaa",
        totalPoints: "Qabxii waliigalaa",
      },
      groups: {
        title: "Tilmaama garee",
        locked: "Qufame",
        open: "Banaa",
        notSelected: "Hin filatamne",
      },
      daily: {
        title: "Tilmaama guyyoo",
        submitted: "Tilmaama galchame",
        notSubmitted: "Hin galchamne",
        finalResult: "Bu'aa xumuraa",
        pending: "Eegamaa",
        pointsGained: "Qabxii argame",
        status: "Haala",
      },
    },
    deposit: {
      title: "Dabaluu",
      payTo: "Lakkoofsa kanaaf kaffali:",
      chooseInput: "Gosa raga kaffaltii filadhu",
      modeText: "Qabiyyee/Linki maxxansi",
      modeScreenshot: "Suuraa (screenshot) fe'i",
      pasteLabel: "Ergaa yookaan linkii raga kaffaltii maxxansi",
      pastePlaceholder: "Qabiyyee yookaan linkii tajaajilaa maxxansi...",
      uploadLabel: "Suuraa kaffaltii fe'i",
      chooseDifferent: "Suuraa biraa filadhu",
      chooseImage: "Suuraa filadhu",
      fileHint: "PNG, JPG ykn WEBP hanga 5MB",
      selected: "Filatame: {{name}}",
      confirmPaid: "Kaffaltii raawwadheera jedhee mirkaneessa",
      checkReceipt: "Raga mirkaneessi",
      verifying: "Mirkaneessaa...",
      verifyingPayment: "Kaffaltii mirkaneessaa...",
      errorConfirm: "Mirkaneessaa keessa galchi duraan filadhu.",
      errorEmptyText: "Ergaa yookaan linkii maxxansi.",
      errorNoScreenshot: "Dura suuraa fe'i.",
      errorReceiptFailed: "Ragaan hin mirkaneeffamne.",
      errorOcrFailed: "Suuraa dubbisuu hin dandeenye.",
      successDefault: "Ragaan xumurame. Haala: {{status}}.",
      errorBackend: "Backend waliin walitti dhufeenya hin arganne.",
    },
    withdraw: {
      title: "Baafachuu",
      balance: "Haftee kee",
      min: "Baafachuun xiqqaa: {{min}} Birr",
      max: "Baafachuun guddaa: {{max}} Birr",
      label: "Hamma baafachuu",
      placeholder: "Hamman baafachuu galchi",
      submit: "Baafachuu",
      sending: "Ergaa...",
      errorUser: "Tajaajilamaan hin argamne. Telegram irraa bani.",
      errorMin: "Baafachuun xiqqaa {{min}} dha.",
      errorMax: "Hamman baafachuu haftee caala.",
      errorFailed: "Baafachuu hin milkoofne.",
      errorRequestFailed: "Gaaffiin baafachuu hin ergamne.",
      successDefault: "Gaaffiin baafachuu ergame.",
    },
    game: {
      loading: "Tapha fe'aa jira...",
      fee: "Kaffaltii",
      pick: "Filadhu",
      lay: "Kaa'i",
      empty: "Duwwaa",
      player: "Taphataa",
      gameOver: "Tapha xumurame",
      winner: "Injifataa",
      pattern: "Qaamolee",
      reason: "Sababa",
      ended: "Xumurame",
      notAvailable: "Hin jiru",
      leave: "Ba'i",
      starting: "Jalqabaa...",
      playAgain: "Irra deebi'ii taphadhu",
      you: "Ati",
      waiting: "Kaardii eegaa...",
      win: "Injifadhu",
      errorNetwork: "Dogoggora network. Server waliin walitti hin dhufne.",
      errorAction: "Tarkaanfiin hin milkoofne",
      errorPickFirst: "Dursee kaardii filadhu; booda kaa'i.",
      errorAlreadyPicked: "Dursee filatte; kaardii tokko kaa'uu qabda.",
      errorWinningHand: "Harkaan injifannoo 4-3-3-1 ta'uu qaba.",
      statusFee: "Kaffaltii: {{amount}} Birr",
      statusPlayer: "Taphataa {{id}}",
      statusWinner: "Injifataa: Taphataa {{id}}",
      statusPattern: "Qaamolee: {{pattern}}",
      statusReason: "Sababa: {{reason}}",
      statusEnded: "Xumurame: {{ended}}",
    },
  },
};

const translationPatches = {
  en: {
    raffle: {
      brand: "mgnot",
      subtitle: "ምኞት",
      nav: { home: "Home", tickets: "Your tickets", numbers: "Available numbers", winners: "Past winners" },
    },
  },
  am: {
    raffle: {
      brand: "mgnot",
      subtitle: "ምኞት",
      nav: { home: "መነሻ", tickets: "የእርስዎ ትኬቶች", numbers: "ክፍት ቁጥሮች", winners: "ያለፉ አሸናፊዎች" },
    },
    common: {
      saved: "ተቀምጧል",
      cancel: "ሰርዝ",
      save: "አስቀምጥ",
      remove: "አስወግድ",
      validating: "በማረጋገጥ ላይ...",
      pointsShort: "{{count}} ነጥብ",
    },
    currency: {
      birr: "ብር",
      amount: "{{amount}} ብር",
      pool: "{{amount}} ብር ፑል",
    },
    nav: {
      home: "መነሻ",
      groupStage: "የቡድን ደረጃ",
      playoffs: "ፕሌይ ኦፍ",
    },
    profile: {
      noPools: "እስካሁን የተቀላቀሉት ፑል የለም።",
      joinedPools: "የተቀላቀሉ ፑሎች",
      pool: "ፑል",
      rank: "ደረጃ",
      points: "ነጥብ",
      totalPoints: "ጠቅላላ ነጥብ",
      bestRank: "ምርጥ ደረጃ",
      lockedGroups: "የተቆለፉ ቡድኖች",
      account: "መለያ",
    },
    betSlip: {
      bet: "ውርርድ",
      bets: "ውርርዶች",
      title: "የውርርድ ዝርዝር",
      oneSelection: "1 ምርጫ",
      selections: "{{count}} ምርጫዎች",
      saveToPools: "ወደ ፑሎች አስቀምጥ",
      joinFirst: "መጀመሪያ ፑል ይቀላቀሉ።",
      selectPool: "ውርርዶችን ከማስቀመጥ በፊት ቢያንስ አንድ ፑል ይምረጡ።",
      success: "ውርርዶች በተሳካ ሁኔታ ተቀመጡ።",
      failed: "ውርርዶችን ማስቀመጥ አልተቻለም።",
      minimize: "የውርርድ ዝርዝሩን አሳንስ",
      saving: "በማስቀመጥ ላይ...",
    },
    home: {
      pools: {
        joinedProgress: "ተቀላቅለዋል {{count}}%",
        first: "1ኛ",
        second: "2ኛ",
        third: "3ኛ",
      },
    },
    poolSelection: {
      screenshotReadFailed: "ስክሪንሾቱን ማንበብ አልተቻለም።",
      pasteReceiptFirst: "መጀመሪያ የቴሌብር መልዕክት ወይም ሊንክ ይለጥፉ።",
      uploadScreenshotFirst: "መጀመሪያ የቴሌብር ስክሪንሾት ይጫኑ።",
      poolTitle: "{{amount}} ብር ፑል",
      payTitle: "{{amount}} ብር በቴሌብር ይክፈሉ",
      payBody: "ለ{{amount}} ብር ፑል በትክክል {{amount}} ብር ይላኩ፣ ከዚያ የቴሌብር መልዕክት/ሊንክ ይለጥፉ ወይም ስክሪንሾት ይጫኑ።",
      message: "መልዕክት",
      screenshot: "ስክሪንሾት",
      receiptPlaceholder: "የቴሌብር መልዕክት ወይም ሊንክ ይለጥፉ...",
      screenshotPreviewAlt: "የቴሌብር ክፍያ ስክሪንሾት ቅድመ እይታ",
      validatePayment: "ክፍያ አረጋግጥ",
    },
    group: {
      summary: {
        lockedGroups: "የተቆለፉ ቡድኖች",
      },
      predictionPool: "የትንበያ ፑል",
      selectPool: "ፑል ይምረጡ",
      joinAnotherPool: "ሌላ ፑል ይቀላቀሉ",
      possiblePoints: "ሊገኙ የሚችሉ ነጥቦች",
      groupSaved: "{{group}} ተቀምጧል",
      groupLocked: "{{group}} ተቆልፏል",
      saveFailed: "ቡድኑን ማስቀመጥ አልተቻለም",
      lockFailed: "ቡድኑን መቆለፍ አልተቻለም",
      lockGroup: "{{group}} ቆልፍ",
    },
  },
  om: {
    raffle: {
      brand: "mgnot",
      subtitle: "ምኞት",
      nav: { home: "Fuula jalqabaa", tickets: "Tikeetota kee", numbers: "Lakkoofsota banaa", winners: "Mo'attoota darban" },
    },
    common: {
      saved: "Olkaa'e",
      cancel: "Haqi",
      save: "Olkaa'i",
      remove: "Haqi",
      validating: "Mirkaneessaa jira...",
      pointsShort: "{{count}} qabxii",
    },
    currency: {
      birr: "Birr",
      amount: "{{amount}} Birr",
      pool: "{{amount}} Birr poolii",
    },
    nav: {
      home: "Fuula jalqabaa",
      groupStage: "Sadarkaa garee",
      playoffs: "Play offs",
    },
    profile: {
      noPools: "Poolii seentan hin jiru.",
      joinedPools: "Poolii seentan",
      pool: "Poolii",
      rank: "Sadarkaa",
      points: "Qabxii",
      totalPoints: "Qabxii waliigalaa",
      bestRank: "Sadarkaa gaarii",
      lockedGroups: "Gareewwan qufaman",
      account: "Akkaawuntii",
    },
    betSlip: {
      bet: "Filannoo",
      bets: "Filannoowwan",
      title: "Waraqaa tilmaamaa",
      oneSelection: "Filannoo 1",
      selections: "Filannoo {{count}}",
      saveToPools: "Pooliitti olkaa'i",
      joinFirst: "Jalqaba poolii seeni.",
      selectPool: "Tilmaama olkaa'uuf yoo xiqqaate poolii tokko filadhu.",
      success: "Tilmaamni milkaa'inaan olkaa'ame.",
      failed: "Tilmaama olkaa'uun hin danda'amne.",
      minimize: "Waraqaa tilmaamaa xiqqeessi",
      saving: "Olkaa'aa jira...",
    },
    home: {
      pools: {
        joinedProgress: "Seente {{count}}%",
        first: "1ffaa",
        second: "2ffaa",
        third: "3ffaa",
      },
    },
    poolSelection: {
      screenshotReadFailed: "Suuraa dubbisuun hin danda'amne.",
      pasteReceiptFirst: "Jalqaba ergaa yookaan linkii Telebirr maxxansi.",
      uploadScreenshotFirst: "Jalqaba suuraa Telebirr fe'i.",
      poolTitle: "{{amount}} Birr Poolii",
      payTitle: "{{amount}} Birr Telebirr'n kaffali",
      payBody: "Poolii {{amount}} Birr'f sirriitti {{amount}} Birr ergi; booda ergaa/linkii Telebirr maxxansi yookaan suuraa fe'i.",
      message: "Ergaa",
      screenshot: "Suuraa",
      receiptPlaceholder: "Ergaa yookaan linkii Telebirr maxxansi...",
      screenshotPreviewAlt: "Durargii suuraa kaffaltii Telebirr",
      validatePayment: "Kaffaltii mirkaneessi",
    },
    group: {
      summary: {
        lockedGroups: "Gareewwan qufaman",
      },
      predictionPool: "Poolii tilmaamaa",
      selectPool: "Poolii filadhu",
      joinAnotherPool: "Poolii biraa seeni",
      possiblePoints: "Qabxii argamuu danda'u",
      groupSaved: "{{group}} olkaa'e",
      groupLocked: "{{group}} qufame",
      saveFailed: "Garee olkaa'uun hin danda'amne",
      lockFailed: "Garee qufachuun hin danda'amne",
      lockGroup: "{{group}} qufi",
    },
  },
};

const raffleUiPatches = {
  en: {
    tagline: "Wish it. Get it.",
    successTitle: "Ticket confirmed!", contactHelp: "Contact & help", contactBody: "Need help with a ticket or payment? Our support team is ready.",
    telegramSupport: "Telegram support", callSupport: "Call support", chooseNumberFirst: "First, choose your number",
    selectNumberIntro: "Select an available lucky number for this item.", confirmNumberLabel: "Confirm your number",
    confirmNumberTitle: "Is this your lucky number?", confirmNumberBody: "You are choosing number {{number}} for {{item}}.",
    chooseAnother: "Choose another", yesContinue: "Yes, continue", paymentStep: "Payment & receipt",
    availablePercent: "{{count}}% available", left: "Left", sold: "Sold", total: "Total", viewItem: "View item",
    available: "Available", taken: "Taken", selected: "Selected", numberAria: "Number {{number}}, {{status}}",
    numberHelp: "Choose one number from 1 to {{limit}}. Once saved, the ticket is final.",
    failedTickets: "Failed to load your tickets.", failedWinners: "Failed to load winners.", failedNumbers: "Failed to load available numbers.",
    screenshotReadFailed: "Could not read that screenshot.", telegramRequired: "Open this app from Telegram before buying a ticket.",
    pasteReceipt: "Paste the Telebirr message or link first.", uploadScreenshot: "Upload a Telebirr screenshot first.",
    paymentFailed: "Payment could not be validated.", chooseAvailable: "Choose an available number first.", saveFailed: "Could not save your ticket number.",
    success: "Ticket #{{number}} is saved for {{item}}. Good luck!", pendingTitle: "{{count}} paid ticket is waiting for a number.",
    paymentSafe: "Your payment is safe. Choose a number when you are ready.", chooseFor: "Choose for {{item}}",
    loadingRaffles: "Loading item raffles...", showLess: "Show less", seeMore: "See more ({{count}})", previousWinners: "Previous item winners",
    item: "Item", winner: "Winner", winningNumber: "Winning number", phone: "Phone", close: "Close",
    galleryAlt: "{{item}} view {{number}}", condition: "Condition", ticketPrice: "Ticket price", readMore: "Read more",
    buyTicket: "Buy ticket — {{price}}", soldOut: "Sold out", step1: "Step 1 of 2 · Validate payment", payWith: "Pay {{price}} with Telebirr",
    paymentInstructions: "Send the exact ticket price, then paste the message/link or upload a clear screenshot.",
    messageLink: "Message or link", screenshot: "Screenshot", receiptPlaceholder: "Paste the Telebirr message or link...",
    previewAlt: "Payment screenshot preview", back: "Back", validating: "Validating...", validatePayment: "Validate payment",
    step2: "Step 2 of 2 · Choose your lucky number", paymentConfirmed: "Payment confirmed",
    numberInstructions: "One ticket place is reserved for you. Choose an available number below, or return later.",
    chooseLater: "Choose later", saving: "Saving...", saveTicket: "Save ticket #{{number}}", chooseNumber: "Choose number",
    yourTickets: "Your tickets", ticketCount: "{{count}} ticket", loadingTickets: "Loading your tickets...", noTickets: "You do not have any tickets yet.",
    buyFirst: "Choose an item from the home page to buy your first ticket.", viewItems: "View items", ticketPriceValue: "{{price}} ticket",
    ticketNumber: "Ticket number", notSelected: "Not selected", status: "Status", active: "Active",
    english: "English", amharic: "Amharic", oromifa: "Oromifa", openProfile: "Open profile", telegramUser: "Telegram user",
    loading: "Loading...", telegramOffline: "Telegram sync offline", connectedAccount: "Connected account", ownedTickets: "Owned tickets",
    noProfileTickets: "You have not bought a raffle ticket yet.", ticketAssigned: "Ticket #{{number}}",
    paymentPending: "Payment confirmed — number pending", raffleSections: "Raffle sections",
    noDrawToday: "No draw for today", drawResult: "Draw result", drawingFor: "Drawing for", completed: "Completed",
    drawingIn: "Drawing in", startsIn: "Starts in", liveDraw: "Live draw", takenNumbers: "Taken numbers",
    drawInProgress: "Draw in progress", winnerSelected: "Winning ticket selected", mixingTickets: "Selecting the winning ticket…",
    drawApproaching: "The reels speed up as the draw gets closer.", waitingForDraw: "The digit reels start during the final 24 hours.",
    yourEntries: "Your entries", yourTicketNumbers: "Ticket numbers you bought", confirmedEntry: "Confirmed entry",
    numberPending: "Number pending", noTicketsForDraw: "You have no tickets in this draw.", youWon: "Winner", notWinner: "Not selected as winner",
  },
  am: {
    tagline: "ይመኙት። ያግኙት።",
    successTitle: "ትኬቱ ተረጋግጧል!", contactHelp: "ያግኙን እና እገዛ", contactBody: "ለትኬት ወይም ክፍያ እገዛ ይፈልጋሉ? የድጋፍ ቡድናችን ዝግጁ ነው።",
    telegramSupport: "የቴሌግራም ድጋፍ", callSupport: "ወደ ድጋፍ ይደውሉ", chooseNumberFirst: "መጀመሪያ ቁጥርዎን ይምረጡ",
    selectNumberIntro: "ለዚህ ዕቃ የሚገኝ የዕድል ቁጥር ይምረጡ።", confirmNumberLabel: "ቁጥርዎን ያረጋግጡ",
    confirmNumberTitle: "ይህ የዕድል ቁጥርዎ ነው?", confirmNumberBody: "ለ{{item}} ቁጥር {{number}}ን እየመረጡ ነው።",
    chooseAnother: "ሌላ ይምረጡ", yesContinue: "አዎ፣ ቀጥል", paymentStep: "ክፍያ እና ደረሰኝ",
    availablePercent: "{{count}}% ይገኛል", left: "የቀረ", sold: "የተሸጠ", total: "ጠቅላላ", viewItem: "ዕቃውን ይመልከቱ",
    available: "የሚገኝ", taken: "የተያዘ", selected: "የተመረጠ", numberAria: "ቁጥር {{number}}፣ {{status}}",
    numberHelp: "ከ1 እስከ {{limit}} አንድ ቁጥር ይምረጡ። ከተቀመጠ በኋላ ትኬቱ ቋሚ ነው።",
    failedTickets: "ትኬቶችዎን መጫን አልተቻለም።", failedWinners: "አሸናፊዎችን መጫን አልተቻለም።", failedNumbers: "የሚገኙ ቁጥሮችን መጫን አልተቻለም።",
    screenshotReadFailed: "ስክሪንሾቱን ማንበብ አልተቻለም።", telegramRequired: "ትኬት ከመግዛትዎ በፊት መተግበሪያውን ከቴሌግራም ይክፈቱ።",
    pasteReceipt: "መጀመሪያ የቴሌብር መልዕክት ወይም ሊንክ ይለጥፉ።", uploadScreenshot: "መጀመሪያ የቴሌብር ስክሪንሾት ይጫኑ።",
    paymentFailed: "ክፍያውን ማረጋገጥ አልተቻለም።", chooseAvailable: "መጀመሪያ የሚገኝ ቁጥር ይምረጡ።", saveFailed: "የትኬት ቁጥሩን ማስቀመጥ አልተቻለም።",
    success: "ትኬት #{{number}} ለ{{item}} ተቀምጧል። መልካም ዕድል!", pendingTitle: "{{count}} የተከፈለ ትኬት ቁጥር እየጠበቀ ነው።",
    paymentSafe: "ክፍያዎ ደህንነቱ የተጠበቀ ነው። ሲፈልጉ ቁጥር ይምረጡ።", chooseFor: "ለ{{item}} ይምረጡ",
    loadingRaffles: "የዕቃ ዕጣዎችን በመጫን ላይ...", showLess: "ያነሰ አሳይ", seeMore: "ተጨማሪ ይመልከቱ ({{count}})", previousWinners: "የቀድሞ የዕቃ አሸናፊዎች",
    item: "ዕቃ", winner: "አሸናፊ", winningNumber: "አሸናፊ ቁጥር", phone: "ስልክ", close: "ዝጋ",
    galleryAlt: "የ{{item}} እይታ {{number}}", condition: "ሁኔታ", ticketPrice: "የትኬት ዋጋ", readMore: "ተጨማሪ ያንብቡ",
    buyTicket: "ትኬት ይግዙ — {{price}}", soldOut: "ተሽጧል", step1: "ደረጃ 1 ከ2 · ክፍያ ያረጋግጡ", payWith: "{{price}} በቴሌብር ይክፈሉ",
    paymentInstructions: "ትክክለኛውን የትኬት ዋጋ ይላኩ፣ ከዚያ መልዕክቱን/ሊንኩን ይለጥፉ ወይም ግልጽ ስክሪንሾት ይጫኑ።",
    messageLink: "መልዕክት ወይም ሊንክ", screenshot: "ስክሪንሾት", receiptPlaceholder: "የቴሌብር መልዕክት ወይም ሊንክ ይለጥፉ...",
    previewAlt: "የክፍያ ስክሪንሾት ቅድመ እይታ", back: "ተመለስ", validating: "በማረጋገጥ ላይ...", validatePayment: "ክፍያ ያረጋግጡ",
    step2: "ደረጃ 2 ከ2 · የዕድል ቁጥርዎን ይምረጡ", paymentConfirmed: "ክፍያው ተረጋግጧል",
    numberInstructions: "አንድ የትኬት ቦታ ተይዞልዎታል። ከታች የሚገኝ ቁጥር ይምረጡ፤ በኋላም መመለስ ይችላሉ።",
    chooseLater: "በኋላ ይምረጡ", saving: "በማስቀመጥ ላይ...", saveTicket: "ትኬት #{{number}} አስቀምጥ", chooseNumber: "ቁጥር ይምረጡ",
    yourTickets: "የእርስዎ ትኬቶች", ticketCount: "{{count}} ትኬት", loadingTickets: "ትኬቶችዎን በመጫን ላይ...", noTickets: "እስካሁን ምንም ትኬት የለዎትም።",
    buyFirst: "የመጀመሪያ ትኬትዎን ለመግዛት ከመነሻ ገጹ ዕቃ ይምረጡ።", viewItems: "ዕቃዎችን ይመልከቱ", ticketPriceValue: "{{price}} ትኬት",
    ticketNumber: "የትኬት ቁጥር", notSelected: "አልተመረጠም", status: "ሁኔታ", active: "ንቁ",
    english: "እንግሊዝኛ", amharic: "አማርኛ", oromifa: "ኦሮምኛ", openProfile: "ፕሮፋይል ክፈት", telegramUser: "የቴሌግራም ተጠቃሚ",
    loading: "በመጫን ላይ...", telegramOffline: "የቴሌግራም ግንኙነት የለም", connectedAccount: "የተገናኘ መለያ", ownedTickets: "የተያዙ ትኬቶች",
    noProfileTickets: "እስካሁን የዕጣ ትኬት አልገዙም።", ticketAssigned: "ትኬት #{{number}}",
    paymentPending: "ክፍያ ተረጋግጧል — ቁጥር ይጠብቃል", raffleSections: "የዕጣ ክፍሎች",
    noDrawToday: "ዛሬ ዕጣ የለም", drawResult: "የዕጣ ውጤት", drawingFor: "ዕጣ የሚወጣለት", completed: "ተጠናቋል",
    drawingIn: "ዕጣው የሚወጣው በ", startsIn: "የሚጀምረው በ", liveDraw: "ቀጥታ ዕጣ", takenNumbers: "የተያዙ ቁጥሮች",
    drawInProgress: "ዕጣው በሂደት ላይ ነው", winnerSelected: "አሸናፊ ትኬት ተመርጧል", mixingTickets: "አሸናፊ ትኬት በመምረጥ ላይ…",
    drawApproaching: "የዕጣው ጊዜ ሲቃረብ መዞሪያዎቹ ይፈጥናሉ።", waitingForDraw: "መዞሪያዎቹ በመጨረሻዎቹ 24 ሰዓታት ይጀምራሉ።",
    yourEntries: "የእርስዎ ዕድሎች", yourTicketNumbers: "የገዙት የትኬት ቁጥሮች", confirmedEntry: "የተረጋገጠ ዕድል",
    numberPending: "ቁጥር በመጠበቅ ላይ", noTicketsForDraw: "በዚህ ዕጣ ውስጥ ትኬት የለዎትም።", youWon: "አሸናፊ", notWinner: "አሸናፊ ሆኖ አልተመረጠም",
  },
  om: {
    tagline: "Hawwi. Argadhu.",
    successTitle: "Tikeetiin mirkanaa'e!", contactHelp: "Quunnamtii fi gargaarsa", contactBody: "Tikeetii yookaan kaffaltiif gargaarsa barbaaddaa? Gareen keenya qophiidha.",
    telegramSupport: "Gargaarsa Telegram", callSupport: "Gargaarsa bilbili", chooseNumberFirst: "Jalqaba lakkoofsa kee filadhu",
    selectNumberIntro: "Meeshaa kanaaf lakkoofsa carraa banaa filadhu.", confirmNumberLabel: "Lakkoofsa kee mirkaneessi",
    confirmNumberTitle: "Kun lakkoofsa carraa keetii?", confirmNumberBody: "{{item}}-f lakkoofsa {{number}} filachaa jirta.",
    chooseAnother: "Kan biraa filadhu", yesContinue: "Eeyyee, itti fufi", paymentStep: "Kaffaltii fi nagahee",
    availablePercent: "{{count}}% jira", left: "Hafe", sold: "Gurgurame", total: "Waliigala", viewItem: "Meeshaa ilaali",
    available: "Banaa", taken: "Fudhatame", selected: "Filatame", numberAria: "Lakkoofsa {{number}}, {{status}}",
    numberHelp: "Lakkoofsa 1 hanga {{limit}} keessaa tokko filadhu. Erga olkaa'amee booda tikeetichi dhaabbataadha.",
    failedTickets: "Tikeetota kee fe'uun hin danda'amne.", failedWinners: "Mo'attoota fe'uun hin danda'amne.", failedNumbers: "Lakkoofsota banaa fe'uun hin danda'amne.",
    screenshotReadFailed: "Suuraa dubbisuun hin danda'amne.", telegramRequired: "Tikeetii bituu dura appii kana Telegram keessaa bani.",
    pasteReceipt: "Jalqaba ergaa yookaan linkii Telebirr maxxansi.", uploadScreenshot: "Jalqaba suuraa kaffaltii Telebirr fe'i.",
    paymentFailed: "Kaffaltii mirkaneessuun hin danda'amne.", chooseAvailable: "Jalqaba lakkoofsa banaa filadhu.", saveFailed: "Lakkoofsa tikeetii olkaa'uun hin danda'amne.",
    success: "Tikeetiin #{{number}} {{item}} irratti olkaa'ame. Carraa gaarii!", pendingTitle: "Tikeetiin kaffalame {{count}} lakkoofsa eeggachaa jira.",
    paymentSafe: "Kaffaltiin kee nagaadha. Yeroo barbaadde lakkoofsa filadhu.", chooseFor: "{{item}}-f filadhu",
    loadingRaffles: "Carraa meeshaalee fe'aa jira...", showLess: "Xiqqeessi", seeMore: "Dabalata ilaali ({{count}})", previousWinners: "Mo'attoota meeshaalee duraanii",
    item: "Meeshaa", winner: "Mo'ataa", winningNumber: "Lakkoofsa mo'ataa", phone: "Bilbila", close: "Cufi",
    galleryAlt: "Mul'ata {{item}} {{number}}", condition: "Haala", ticketPrice: "Gatii tikeetii", readMore: "Dabalata dubbisi",
    buyTicket: "Tikeetii biti — {{price}}", soldOut: "Gurgurame", step1: "Tarkaanfii 1/2 · Kaffaltii mirkaneessi", payWith: "{{price}} Telebirr'n kaffali",
    paymentInstructions: "Gatii tikeetii sirrii ergi; booda ergaa/linkii maxxansi yookaan suuraa ifaa fe'i.",
    messageLink: "Ergaa yookaan linkii", screenshot: "Suuraa", receiptPlaceholder: "Ergaa yookaan linkii Telebirr maxxansi...",
    previewAlt: "Durargii suuraa kaffaltii", back: "Duubatti", validating: "Mirkaneessaa jira...", validatePayment: "Kaffaltii mirkaneessi",
    step2: "Tarkaanfii 2/2 · Lakkoofsa carraa kee filadhu", paymentConfirmed: "Kaffaltiin mirkanaa'e",
    numberInstructions: "Bakki tikeetii tokko siif qabameera. Lakkoofsa banaa keessaa filadhu; boodarra deebi'uu dandeessa.",
    chooseLater: "Boodarra filadhu", saving: "Olkaa'aa jira...", saveTicket: "Tikeetii #{{number}} olkaa'i", chooseNumber: "Lakkoofsa filadhu",
    yourTickets: "Tikeetota kee", ticketCount: "Tikeetii {{count}}", loadingTickets: "Tikeetota kee fe'aa jira...", noTickets: "Ammatti tikeetii hin qabdu.",
    buyFirst: "Tikeetii jalqabaa bituuf fuula jalqabaa irraa meeshaa filadhu.", viewItems: "Meeshaalee ilaali", ticketPriceValue: "Tikeetii {{price}}",
    ticketNumber: "Lakkoofsa tikeetii", notSelected: "Hin filatamne", status: "Haala", active: "Hojirra",
    english: "Ingiliffa", amharic: "Amaaraa", oromifa: "Oromiffa", openProfile: "Profaayilii bani", telegramUser: "Fayyadamaa Telegram",
    loading: "Fe'aa jira...", telegramOffline: "Telegram walqunnamtii hin qabu", connectedAccount: "Akkaawuntii walqabate", ownedTickets: "Tikeetota qabdu",
    noProfileTickets: "Ammatti tikeetii carraa hin bitne.", ticketAssigned: "Tikeetii #{{number}}",
    paymentPending: "Kaffaltiin mirkanaa'e — lakkoofsa eeggachaa jira", raffleSections: "Kutaa carraa",
    noDrawToday: "Har'a carraan hin jiru", drawResult: "Bu'aa carraa", drawingFor: "Carraan kan ba'uuf", completed: "Xumurame",
    drawingIn: "Carraan ba'uuf", startsIn: "Jalqabuuf", liveDraw: "Carraa kallattii", takenNumbers: "Lakkoofsota qabaman",
    drawInProgress: "Carraan adeemsa irra jira", winnerSelected: "Tikeetiin mo'ataa filatame", mixingTickets: "Tikeetii mo'ataa filachaa jira…",
    drawApproaching: "Yeroon carraa dhiyaachaa yeroo deemu marsaan saffisa.", waitingForDraw: "Marsaan sa'aatii 24 dhumaa keessatti jalqaba.",
    yourEntries: "Carraa kee", yourTicketNumbers: "Lakkoofsota tikeetii bitte", confirmedEntry: "Carraa mirkanaa'e",
    numberPending: "Lakkoofsa eeggachaa jira", noTicketsForDraw: "Carraa kana keessatti tikeetii hin qabdu.", youWon: "Mo'ataa", notWinner: "Mo'ataa ta'ee hin filatamne",
  },
};

const mergeTranslationPatch = (target, patch) => {
  Object.entries(patch).forEach(([key, value]) => {
    if (value && typeof value === "object" && !Array.isArray(value)) {
      target[key] = target[key] || {};
      mergeTranslationPatch(target[key], value);
    } else {
      target[key] = value;
    }
  });
};

Object.entries(translationPatches).forEach(([language, patch]) => {
  mergeTranslationPatch(translations[language], patch);
});

Object.entries(raffleUiPatches).forEach(([language, patch]) => {
  translations[language].raffle = translations[language].raffle || {};
  translations[language].raffle.ui = patch;
});

const raffleExperiencePatches = {
  en: {
    chooseLanguage: "Choose language",
    english: "English",
    amharic: "Amharic",
    oromifa: "Afaan Oromoo",
    introEyebrow: "Item raffle",
    introTitle: "How Mgnot works",
    introBody: "Choose an item you want, select your lucky number, complete the payment, and get a chance to win the item in the draw.",
    introStep1Title: "Choose an item",
    introStep1Body: "Browse the available raffle items and open the one you want.",
    introStep2Title: "Select a number",
    introStep2Body: "Pick one available lucky number from the item’s number list.",
    introStep3Title: "Pay securely",
    introStep3Body: "Pay the ticket price with Telebirr and submit your payment confirmation.",
    introStep4Title: "Wait for the draw",
    introStep4Body: "Your confirmed number enters the draw. If it is selected, you win the item.",
    introStart: "Start choosing",
    showMoreNumbers: "Show more numbers",
    showFewerNumbers: "Show fewer numbers",
    open: "Open",
    onDraw: "On draw",
    finalDraw: "Final draw",
    goToDraw: "Go to draw",
    details: "Details",
    pay: "Pay",
    previousImage: "Previous image",
    nextImage: "Next image",
    showImage: "Show image {{number}}",
    provider: "Provider",
    paymentTitle: "Pay with Telebirr",
    payDestination: "Pay the above amount to the following number in Telebirr.",
    demoPaymentNumber: "Demo Telebirr number",
    phoneLabel: "Your phone number",
    phoneRequired: "Enter a valid phone number before continuing.",
    verifyingPayment: "Verifying payment...",
    goHome: "Go home",
    emptyTicketsShort: "No tickets yet",
  },
  am: {
    chooseLanguage: "ቋንቋ ይምረጡ",
    english: "እንግሊዝኛ",
    amharic: "አማርኛ",
    oromifa: "ኦሮምኛ",
    introEyebrow: "የዕቃ ዕጣ",
    introTitle: "ምኞት እንዴት ይሰራል?",
    introBody: "የሚፈልጉትን ዕቃ ይምረጡ፣ የዕድል ቁጥር ይያዙ፣ ክፍያውን ያጠናቁ እና በዕጣው የማሸነፍ ዕድል ያግኙ።",
    introStep1Title: "ዕቃ ይምረጡ",
    introStep1Body: "ያሉትን የዕጣ ዕቃዎች ይመልከቱ እና የሚፈልጉትን ይክፈቱ።",
    introStep2Title: "ቁጥር ይምረጡ",
    introStep2Body: "ከዕቃው ዝርዝር ውስጥ አንድ የሚገኝ የዕድል ቁጥር ይምረጡ።",
    introStep3Title: "በደህና ይክፈሉ",
    introStep3Body: "የትኬቱን ዋጋ በቴሌብር ይክፈሉ እና የክፍያ ማረጋገጫዎን ያስገቡ።",
    introStep4Title: "ዕጣውን ይጠብቁ",
    introStep4Body: "የተረጋገጠው ቁጥርዎ በዕጣው ይገባል። ቁጥርዎ ከተመረጠ ዕቃውን ያሸንፋሉ።",
    introStart: "መምረጥ ይጀምሩ",
    showMoreNumbers: "ተጨማሪ ቁጥሮችን አሳይ",
    showFewerNumbers: "ጥቂት ቁጥሮችን አሳይ",
    open: "ክፍት",
    onDraw: "በዕጣ ላይ",
    finalDraw: "የመጨረሻ ዕጣ",
    goToDraw: "ወደ ዕጣው ይሂዱ",
    details: "ዝርዝር",
    pay: "ይክፈሉ",
    previousImage: "የቀድሞ ምስል",
    nextImage: "ቀጣይ ምስል",
    showImage: "ምስል {{number}} አሳይ",
    provider: "አቅራቢ",
    paymentTitle: "በቴሌብር ይክፈሉ",
    payDestination: "ከላይ ያለውን መጠን በቴሌብር ወደሚከተለው ቁጥር ይክፈሉ።",
    demoPaymentNumber: "የሙከራ ቴሌብር ቁጥር",
    phoneLabel: "የስልክ ቁጥርዎ",
    phoneRequired: "ከመቀጠልዎ በፊት ትክክለኛ የስልክ ቁጥር ያስገቡ።",
    verifyingPayment: "ክፍያውን በማረጋገጥ ላይ...",
    goHome: "ወደ መነሻ",
    emptyTicketsShort: "እስካሁን ትኬት የለም",
  },
  om: {
    chooseLanguage: "Afaan filadhu",
    english: "Ingiliffa",
    amharic: "Amaaraa",
    oromifa: "Afaan Oromoo",
    introEyebrow: "Carraa meeshaa",
    introTitle: "Mgnot akkamitti hojjeta?",
    introBody: "Meeshaa barbaaddu filadhu, lakkoofsa carraa kee qabadhu, kaffaltii xumuri; carraa keessatti meeshaa sana mo’achuuf hirmaadhu.",
    introStep1Title: "Meeshaa filadhu",
    introStep1Body: "Meeshaalee carraa jiran ilaaliitii isa barbaaddu bani.",
    introStep2Title: "Lakkoofsa filadhu",
    introStep2Body: "Tarree lakkoofsaa keessaa lakkoofsa carraa banaa tokko filadhu.",
    introStep3Title: "Nageenyaan kaffali",
    introStep3Body: "Gatii tikeetii Telebirr’n kaffaliitii ragaa kaffaltii kee ergi.",
    introStep4Title: "Carraa eegi",
    introStep4Body: "Lakkoofsi kee mirkanaa’e carraa keessa seena. Yoo filatame meeshaa sana ni mo’atta.",
    introStart: "Filachuu jalqabi",
    showMoreNumbers: "Lakkoofsota dabalataa agarsiisi",
    showFewerNumbers: "Lakkoofsota muraasa agarsiisi",
    open: "Banaa",
    onDraw: "Carraa irra",
    finalDraw: "Carraa dhumaa",
    goToDraw: "Gara carraatti deemi",
    details: "Bal’ina",
    pay: "Kaffali",
    previousImage: "Suuraa duraa",
    nextImage: "Suuraa itti aanu",
    showImage: "Suuraa {{number}} agarsiisi",
    provider: "Dhiyeessaa",
    paymentTitle: "Telebirr’n kaffali",
    payDestination: "Maallaqa armaan olii Telebirr’n gara lakkoofsa kanaatti kaffali.",
    demoPaymentNumber: "Lakkoofsa Telebirr fakkeenyaa",
    phoneLabel: "Lakkoofsa bilbilaa kee",
    phoneRequired: "Itti fufuu dura lakkoofsa bilbilaa sirrii galchi.",
    verifyingPayment: "Kaffaltii mirkaneessaa jira...",
    goHome: "Gara jalqabaatti",
    emptyTicketsShort: "Tikeetiin ammaaf hin jiru",
  },
};

Object.entries(raffleExperiencePatches).forEach(([language, patch]) => {
  mergeTranslationPatch(translations[language].raffle.ui, patch);
});

translations.en.raffle.nav.draw = "Draw";
translations.am.raffle.nav.draw = "ዕጣ";
translations.om.raffle.nav.draw = "Carraa";

const LanguageContext = createContext({
  language: "am",
  setLanguage: () => {},
  t: (key, fallback) => fallback || key,
  formatCurrency: (amount) => `${amount} Birr`,
});

const getPathValue = (obj, path) => {
  if (!obj) return undefined;
  return path.split(".").reduce((acc, part) => (acc ? acc[part] : undefined), obj);
};

const interpolate = (template, vars) => {
  if (!vars) return template;
  return template.replace(/\{\{(\w+)\}\}/g, (_, key) => {
    const value = vars[key];
    return value === undefined || value === null ? "" : String(value);
  });
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState("am");

  const updateLanguage = useCallback((next) => {
    setLanguage(next);
  }, []);

  const t = useCallback(
    (key, fallback, vars) => {
      const value =
        getPathValue(translations[language], key) ||
        getPathValue(translations.en, key) ||
        fallback ||
        key;
      return interpolate(value, vars);
    },
    [language]
  );

  const contextValue = useMemo(
    () => ({
      language,
      setLanguage: updateLanguage,
      t,
      formatCurrency: (amount) =>
        t("currency.amount", "{{amount}} Birr", {
          amount: Number(amount || 0).toLocaleString(),
        }),
    }),
    [language, updateLanguage, t]
  );

  return <LanguageContext.Provider value={contextValue}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
