export const countryCodeByName = {
  Mexico: "MX",
  "South Africa": "ZA",
  Japan: "JP",
  "New Zealand": "NZ",
  "United States": "US",
  Colombia: "CO",
  Ghana: "GH",
  Australia: "AU",
  Brazil: "BR",
  Denmark: "DK",
  Morocco: "MA",
  "Korea Republic": "KR",
  France: "FR",
  Senegal: "SN",
  Scotland: "GB",
  "Costa Rica": "CR",
  England: "GB",
  Uruguay: "UY",
  Egypt: "EG",
  Qatar: "QA",
  Argentina: "AR",
  Switzerland: "CH",
  Nigeria: "NG",
  "Saudi Arabia": "SA",
  Spain: "ES",
  Croatia: "HR",
  Cameroon: "CM",
  Panama: "PA",
  Portugal: "PT",
  Netherlands: "NL",
  Tunisia: "TN",
  Jamaica: "JM",
  Germany: "DE",
  Ecuador: "EC",
  Iran: "IR",
  Honduras: "HN",
  Belgium: "BE",
  Serbia: "RS",
  Algeria: "DZ",
  Norway: "NO",
  Sweden: "SE",
  Paraguay: "PY",
  Uzbekistan: "UZ",
  Iraq: "IQ",
  Italy: "IT",
  Chile: "CL",
  Mali: "ML",
  Canada: "CA",
};

const names = {
  am: {
    Mexico: "ሜክሲኮ",
    "South Africa": "ደቡብ አፍሪካ",
    Japan: "ጃፓን",
    "New Zealand": "ኒው ዚላንድ",
    "United States": "ዩናይትድ ስቴትስ",
    Colombia: "ኮሎምቢያ",
    Ghana: "ጋና",
    Australia: "አውስትራሊያ",
    Brazil: "ብራዚል",
    Denmark: "ዴንማርክ",
    Morocco: "ሞሮኮ",
    "Korea Republic": "ደቡብ ኮሪያ",
    France: "ፈረንሳይ",
    Senegal: "ሴኔጋል",
    Scotland: "ስኮትላንድ",
    "Costa Rica": "ኮስታ ሪካ",
    England: "እንግሊዝ",
    Uruguay: "ኡራጓይ",
    Egypt: "ግብፅ",
    Qatar: "ኳታር",
    Argentina: "አርጀንቲና",
    Switzerland: "ስዊዘርላንድ",
    Nigeria: "ናይጄሪያ",
    "Saudi Arabia": "ሳውዲ አረቢያ",
    Spain: "ስፔን",
    Croatia: "ክሮኤሽያ",
    Cameroon: "ካሜሩን",
    Panama: "ፓናማ",
    Portugal: "ፖርቱጋል",
    Netherlands: "ኔዘርላንድ",
    Tunisia: "ቱኒዚያ",
    Jamaica: "ጃማይካ",
    Germany: "ጀርመን",
    Ecuador: "ኢኳዶር",
    Iran: "ኢራን",
    Honduras: "ሆንዱራስ",
    Belgium: "ቤልጂየም",
    Serbia: "ሰርቢያ",
    Algeria: "አልጄሪያ",
    Norway: "ኖርዌይ",
    Sweden: "ስዊድን",
    Paraguay: "ፓራጓይ",
    Uzbekistan: "ኡዝቤኪስታን",
    Iraq: "ኢራቅ",
    Italy: "ጣሊያን",
    Chile: "ቺሌ",
    Mali: "ማሊ",
    Canada: "ካናዳ",
  },
  om: {
    Mexico: "Meeksikoo",
    "South Africa": "Afrikaa Kibbaa",
    Japan: "Jaappaan",
    "New Zealand": "Niiw Ziilaand",
    "United States": "Yuunaayitid Isteetis",
    Colombia: "Kolombiyaa",
    Ghana: "Gaanaa",
    Australia: "Awustiraaliyaa",
    Brazil: "Biraaziil",
    Denmark: "Deenmaark",
    Morocco: "Morookoo",
    "Korea Republic": "Kooriyaa Kibbaa",
    France: "Faransaay",
    Senegal: "Senegaal",
    Scotland: "Iskootilaand",
    "Costa Rica": "Koostaa Riikaa",
    England: "Ingilaand",
    Uruguay: "Uraaguwaay",
    Egypt: "Gibxi",
    Qatar: "Qaxar",
    Argentina: "Arjentiinaa",
    Switzerland: "Siwiizarlaand",
    Nigeria: "Naayijeeriyaa",
    "Saudi Arabia": "Saawud Arabiyaa",
    Spain: "Ispeen",
    Croatia: "Kirooshiyaa",
    Cameroon: "Kaameruun",
    Panama: "Paanamaa",
    Portugal: "Poortugaal",
    Netherlands: "Nezerlaand",
    Tunisia: "Tuniiziyaa",
    Jamaica: "Jamaayikaa",
    Germany: "Jarmanii",
    Ecuador: "Ikkuwaadoor",
    Iran: "Iraan",
    Honduras: "Honduraas",
    Belgium: "Beljiyeem",
    Serbia: "Serbiyaa",
    Algeria: "Aljeeriyaa",
    Norway: "Noorweey",
    Sweden: "Siwiidin",
    Paraguay: "Paaragwaay",
    Uzbekistan: "Uzbeekistaan",
    Iraq: "Iraaq",
    Italy: "Xaaliyaan",
    Chile: "Chiilee",
    Mali: "Maalii",
    Canada: "Kanaadaa",
  },
};

export function getCountryName(name, language) {
  return names[language]?.[name] || name;
}
